### ISSUE TITLE
Build zip file missing kseq.h

### ISSUE THREAD

**Issue by azric** [wwood/OrfM#3] opened 2016-02-19 22:52 UTC
I've tried building OrfM from https://github.com/wwood/OrfM/archive/master.zip based on my user's request.
The make died with
src/orfm.c:8:24: fatal error: seqtk/kseq.h: No such file or directory
 #include <seqtk/kseq.h>

I found orfm-0.5.3.tar.gz which appears to be newer than master.zip, and it has ext/seqt/kseq.h which is missing from the master.zip I downloaded today.

Any reason I shouldn't go with the tar version, since it compiles?

**Comment by wwood** [comment] 2016-02-19 23:12
Hi there,

Thanks for your (user's) interest in OrfM.

It seems master on GitHub was out of date, I just fixed that - thanks for noticing - master and 0.5.3 are now at the same commit. However, that is not the cause of your problem. The problem is that `seqtk` is a git submodule, and the master.zip you refer to does not include submodule code as it is autogenerated by GitHub.

I would go with the tar version, or if you really want to build from master, clone recursively, something like this:

```
git clone --recursive https://github.com/wwood/OrfM
```

You'll also need to run `autogen.sh`.
Make sense?
ben

**Comment by azric** [comment] 2016-02-19 23:21
I’ll go with the tar version since it has a configure file and “./configure && make” works like a champ.  In the zip, autogen.sh dies on CentOS6/RHEL6 with “Autoconf 2.69 needed”; CentOS6/RHEL 6 only have autoconf-2.63 even with devtools-3 extensions installed ;-)

Thanks for the fast response.

## Ric

On Feb 19, 2016, at 4:12 PM, Ben J Woodcroft <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi there,

Thanks for your (user's) interest in OrfM.

It seems master on GitHub was out of date, I just fixed that - thanks for noticing - master and 0.5.3 are now at the same commit. However, that is not the cause of your problem. The problem is that seqtk is a git submodule, and the master.zip you refer to does not include submodule code as it is autogenerated by GitHub.

I would go with the tar version, or if you really want to build from master, clone recursively, something like this:

git clone --recursive https://github.com/wwood/OrfM

You'll also need to run autogen.sh.
Make sense?
ben

**Comment by wwood** [comment] 2016-02-19 23:34
Right, I think it also does not work on Ubuntu 12.04 for the same reason so I build on the newest Ubuntu.

Great that it works, I'd not tried it on RH. I'm closing now, let me know if there is anything else.

**Closed as completed by wwood** 2016-02-19 23:34 UTC
